keys:
  - &janinge age1rjrd5zds2ss2rndvh77ae877l9qtpx8adkcah7mr2cp593kmuuqq77348n
  - &hh4_nomad age1hfwhce0u6x47u8e2zn826d38sgw3krp9lu8akdh4mua2e7505u9szl65fd
  - &edge_gw age13g3dmcem79wmq832v4um0wm95gqx25nkn5npl33a66yv9m0a7udshywt3z
  - &lw_gw age1r8myunsfjm29rvzs6lra9sh8lnu93dfyxu8k58kr23qujt062c8sznz074
  - &aws_gw age1ala0nnlnsclr8zg7phd0w53nd5y868u7un4ucggm9v27855fjg7sa4fsc0
  - &cb_weed age1j9jfsf0aw3fkavmndpr4k6wcm0uyzq64jgerz9gace87u8v6659s4shh97
  - &fbv_c2_01 age1jhz6m6kcqj8f5gfddx5zylhjsuuazg767aalgzss3p49dvj9tpys6kh2km
  - &sto_s2_01 age1l7nswqc7dqzc45rsmaspt6x6sppxuwd450fqnd2fc5vvplvmg3msz8r8m2
  - &fra_c2_01 age1xuphm46e8ry72fqy4cy5ac9n0ejchr8trql4dlgjpcdgdn7hdp0srg6rrl
  - &ams_c1_01 age1whhsvuteq2p8wmpt7swft4fn42ztmwp2whwk0w9dsnqsgz2znv0shp2c84
  - &ams_c1_02 age1lqaag35cf5ykruelqefc3vjm5j902473s2wd4zvg7kxpjyhw2pjsxyckhk
  - &ams_c2_02 age1s32geg33v4qq2rzmhehvdn2ggr4l4t58jmqu4u08t0yh0qnqka5spv0san
  - &ams_c2_03 age184lqlx97vzd58gsyw4ggysr9m70y7cxejdy9qluedwh5nnzyd9dsysw48m

creation_rules:
  # Site specific: hh4
  - path_regex: secrets/hh4\.yaml$
    key_groups:
      - age:
          - *janinge
          - *hh4_nomad

  # Specific to Kata Containers
  - path_regex: secrets/kata\.yaml$
    key_groups:
      - age:
          - *janinge
          - *fra_c2_01
          - *ams_c2_02

  # Shared global secrets
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *janinge
          - *hh4_nomad
          - *edge_gw
          - *lw_gw
          - *aws_gw
          - *cb_weed
          - *fbv_c2_01
          - *sto_s2_01
          - *fra_c2_01
          - *ams_c1_01
          - *ams_c1_02
          - *ams_c2_02
          - *ams_c2_03

